import { GitRepo } from "./git-repo";

export interface User {
    login: string,
    id: number,
    avatar_url: string,
    url: string,
    followers_url: string,
    repos_url: string,
    languages: string[],
    gravatar_id?: string,
    html_url?: string,
    following_url?: string,
    gists_url?: string,
    starred_url?: string,
    subscriptions_url?: string,
    organizations_url?: string,
    events_url?: string,
    received_events_url?: string,
    site_admin?: string,
    name?: string,
    company?: string,
    blog?: string,
    location?: string,
    email?: string,
    hireable?: string,
    bio?: string,
    twitter_username?: string,
    public_repos?: number,
    public_gists?: number,
    followers: number,
    following?: number,
    repos?: GitRepo[],
    score: number
}